insert into Statistic(Id, StatisticType_Id, Value) values (1, 1, 10);
insert into Statistic(Id, StatisticType_Id, Value) values (2, 1, 11);
insert into Statistic(Id, StatisticType_Id, Value) values (3, 1, 12);
insert into Statistic(Id, StatisticType_Id, Value) values (4, 2, 20);
insert into Statistic(Id, StatisticType_Id, Value) values (5, 2, 21);
insert into Statistic(Id, StatisticType_Id, Value) values (6, 2, 22);
insert into Statistic(Id, StatisticType_Id, Value) values (7, 2, 23);
insert into Statistic(Id, StatisticType_Id, Value) values (8, 3, 30);
insert into Statistic(Id, StatisticType_Id, Value) values (9, 3, 31);